[package]
name = "ChainlinkPlatform"
version = "1.0.0"
authors = []

[addresses]
platform = "_"
aave_oracle_racc_address = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
