[package]
name = "AaveData"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
aave_data = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AaveConfig = { local = "../aave-config" }
AaveMath = { local = "../aave-math" }
AavePool = { local = "../" }

[dev-dependencies]
