[package]
name = "ChainlinkDataFeeds"
version = "1.0.0"
authors = []

[addresses]
data_feeds = "_"
aave_oracle_racc_address = "_"
platform = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkPlatform = { local = "../chainlink-platform" }

[dev-dependencies]
